name: gitleaks

on:
    pull_request:
    push:
        branches: [ master, develop ]

jobs:
    gitleaks:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Run gitleaks
              uses: zricethezav/gitleaks-action@master
